<!DOCTYPE html>
<html>
<head>
	<title>Image slider generated by WOWSlider.com</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="description" content="Made with WOW Slider - Create beautiful, responsive image sliders in a few clicks. Awesome skins and animations. Image slider" />
	
	<!-- Start WOWSlider.com HEAD section --> <!-- add to the <head> of your page -->
	<link rel="stylesheet" type="text/css" href="engine1/style.css" />
	<script type="text/javascript" src="engine1/jquery.js"></script>
	<!-- End WOWSlider.com HEAD section -->

</head>
<body style="background-color:#d7d7d7;margin:0">
	
	<div id="wowslider-container1">
	<div class="ws_images"><ul>
		<li><img src="data1/images/photo_20161022_180748.jpg" alt="photo_2016-10-22_18-07-48" title="photo_2016-10-22_18-07-48" id="wows1_0"/></li>
		<li><a href="http://wowslider.com/vi"><img src="data1/images/photo_20161022_180755.jpg" alt="slideshow html" title="photo_2016-10-22_18-07-55" id="wows1_1"/></a></li>
		<li><img src="data1/images/photo_20161022_180802.jpg" alt="photo_2016-10-22_18-08-02" title="photo_2016-10-22_18-08-02" id="wows1_2"/></li>
	</ul></div>
	<div class="ws_bullets"><div>
		<a href="#" title="photo_2016-10-22_18-07-48"><span><img src="data1/tooltips/photo_20161022_180748.jpg" alt="photo_2016-10-22_18-07-48"/>1</span></a>
		<a href="#" title="photo_2016-10-22_18-07-55"><span><img src="data1/tooltips/photo_20161022_180755.jpg" alt="photo_2016-10-22_18-07-55"/>2</span></a>
		<a href="#" title="photo_2016-10-22_18-08-02"><span><img src="data1/tooltips/photo_20161022_180802.jpg" alt="photo_2016-10-22_18-08-02"/>3</span></a>
	</div></div><div class="ws_script" style="position:absolute;left:-99%"><a href="http://wowslider.com">image slider</a> by WOWSlider.com v7.7</div>
	<div class="ws_shadow"></div>
	</div>	


	<script type="text/javascript" src="engine1/wowslider.js"></script>
	<script type="text/javascript" src="engine1/script.js"></script>
	<!-- End WOWSlider.com BODY section -->

</body>
</html>